/* =====================================================================
 * スト6コンボメーカー  シードデータ
 *  - frames.jp / frames.ryu は公式サイト(streetfighter.com)から取得した実データ
 *  - combos / setplays はユーザーが追加していく想定（リュウは例として同梱）
 *  - 他キャラ追加: characters に1行足し、frames/combos 等にキー追加
 * ===================================================================*/

const SF6_DATA = {
  "characters": [
    {
      "id": "ryu",
      "name": "リュウ",
      "color": "#d23b3b"
    },
    {
      "id": "luke",
      "name": "ルーク",
      "color": "#3b78d2"
    },
    {
      "id": "jamie",
      "name": "ジェイミー",
      "color": "#3bbf6f"
    },
    {
      "id": "chunli",
      "name": "春麗",
      "color": "#e0a52a"
    },
    {
      "id": "guile",
      "name": "ガイル",
      "color": "#9b59b6"
    },
    {
      "id": "kimberly",
      "name": "キンバリー",
      "color": "#1abc9c"
    },
    {
      "id": "juri",
      "name": "ジュリ",
      "color": "#e0533b"
    },
    {
      "id": "ken",
      "name": "ケン",
      "color": "#5b6cd2"
    },
    {
      "id": "blanka",
      "name": "ブランカ",
      "color": "#cc6fa8"
    },
    {
      "id": "dhalsim",
      "name": "ダルシム",
      "color": "#4a9bd1"
    },
    {
      "id": "ehonda",
      "name": "エドモンド本田",
      "color": "#d23b3b"
    },
    {
      "id": "deejay",
      "name": "ディージェイ",
      "color": "#3b78d2"
    },
    {
      "id": "manon",
      "name": "マノン",
      "color": "#3bbf6f"
    },
    {
      "id": "marisa",
      "name": "マリーザ",
      "color": "#e0a52a"
    },
    {
      "id": "jp",
      "name": "JP",
      "color": "#9b59b6"
    },
    {
      "id": "zangief",
      "name": "ザンギエフ",
      "color": "#1abc9c"
    },
    {
      "id": "lily",
      "name": "リリー",
      "color": "#e0533b"
    },
    {
      "id": "cammy",
      "name": "キャミィ",
      "color": "#5b6cd2"
    },
    {
      "id": "rashid",
      "name": "ラシード",
      "color": "#cc6fa8"
    },
    {
      "id": "aki",
      "name": "A.K.I.",
      "color": "#4a9bd1"
    },
    {
      "id": "ed",
      "name": "ED",
      "color": "#d23b3b"
    },
    {
      "id": "gouki_akuma",
      "name": "豪鬼",
      "color": "#3b78d2"
    },
    {
      "id": "vega_mbison",
      "name": "ベガ",
      "color": "#3bbf6f"
    },
    {
      "id": "terry",
      "name": "テリー",
      "color": "#e0a52a"
    },
    {
      "id": "mai",
      "name": "舞",
      "color": "#9b59b6"
    },
    {
      "id": "elena",
      "name": "エレナ",
      "color": "#1abc9c"
    },
    {
      "id": "sagat",
      "name": "サガット",
      "color": "#e0533b"
    },
    {
      "id": "cviper",
      "name": "C.ヴァイパー",
      "color": "#5b6cd2"
    },
    {
      "id": "alex",
      "name": "アレックス",
      "color": "#cc6fa8"
    },
    {
      "id": "ingrid",
      "name": "イングリッド",
      "color": "#4a9bd1"
    }
  ],
  "combos": {
    "jp": [],
    "ryu": [
      {
        "id": "ryu-c1",
        "name": "基本中央ヒット確認",
        "start": "通常ヒット",
        "notation": "2中K > 弱波動拳",
        "damage": 1300,
        "drive": 0,
        "super": 1,
        "difficulty": 1,
        "position": "中央",
        "video": "",
        "note": "削り・牽制から。安全に締める基本。"
      },
      {
        "id": "ryu-c2",
        "name": "パニカン standard",
        "start": "パニッシュカウンター",
        "notation": "中P > 5中P > 強昇龍拳",
        "damage": 2600,
        "drive": 1,
        "super": 2,
        "difficulty": 2,
        "position": "中央",
        "video": "",
        "note": "確反からの基本火力。"
      },
      {
        "id": "ryu-c3",
        "name": "ドライブラッシュ始動",
        "start": "ドライブラッシュ",
        "notation": "DR中P > 大P > 中竜巻 > OD昇龍",
        "damage": 3400,
        "drive": 3,
        "super": 2,
        "difficulty": 3,
        "position": "中央",
        "video": "",
        "note": "ゲージ使用の主力。運び込み。"
      }
    ]
  },
  "frames": {
    "jp": [
      {
        "move": "立ち弱P（ノーシ）",
        "type": "通常技",
        "command": "弱P",
        "startup": 6,
        "active": "6-8",
        "recovery": "10",
        "onHit": 4,
        "onBlock": -2,
        "cancel": "C",
        "damage": "300",
        "comboCorrect": "始動補正20%",
        "driveGain": "250",
        "driveLoseGuard": "-500",
        "driveLosePunish": "-2000",
        "saGain": "300",
        "attribute": "上",
        "note": "連打キャンセル対応"
      },
      {
        "move": "立ち弱K（ニージニイ・ウダール）",
        "type": "通常技",
        "command": "弱K",
        "startup": 5,
        "active": "5-7",
        "recovery": "11",
        "onHit": 3,
        "onBlock": -2,
        "cancel": "C",
        "damage": "300",
        "comboCorrect": "始動補正20%",
        "driveGain": "250",
        "driveLoseGuard": "-500",
        "driveLosePunish": "-2000",
        "saGain": "300",
        "attribute": "上",
        "note": ""
      },
      {
        "move": "立ち中P（シュトゥールム）",
        "type": "通常技",
        "command": "中P",
        "startup": 12,
        "active": "12-14",
        "recovery": "21",
        "onHit": 1,
        "onBlock": -6,
        "cancel": "※",
        "damage": "700",
        "comboCorrect": "",
        "driveGain": "3000",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-6000",
        "saGain": "500",
        "attribute": "上",
        "note": "※ヴィーハト・チェーニのみキャンセル可能"
      },
      {
        "move": "立ち中K（ウームヌィ・ウダール）",
        "type": "通常技",
        "command": "中K",
        "startup": 8,
        "active": "8-10",
        "recovery": "19",
        "onHit": 3,
        "onBlock": -3,
        "cancel": "C",
        "damage": "600",
        "comboCorrect": "",
        "driveGain": "1500",
        "driveLoseGuard": "-3000",
        "driveLosePunish": "-4000",
        "saGain": "500",
        "attribute": "上",
        "note": ""
      },
      {
        "move": "立ち強P（キンターヴル）",
        "type": "通常技",
        "command": "強P",
        "startup": 12,
        "active": "12-13",
        "recovery": "22",
        "onHit": 3,
        "onBlock": -3,
        "cancel": "C",
        "damage": "800",
        "comboCorrect": "始動補正20%",
        "driveGain": "2000",
        "driveLoseGuard": "-5000",
        "driveLosePunish": "-8000",
        "saGain": "1000",
        "attribute": "上",
        "note": "空中ヒット時吹き飛びダウン / パニッシュカウンター時+25F"
      },
      {
        "move": "立ち強K（オボロートニ）",
        "type": "通常技",
        "command": "強K",
        "startup": 12,
        "active": "12-15",
        "recovery": "17",
        "onHit": 7,
        "onBlock": 2,
        "cancel": "",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "3000",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-10000",
        "saGain": "1000",
        "attribute": "上",
        "note": "※ヴィーハト・チェーニのみキャンセル可能"
      },
      {
        "move": "しゃがみ弱P（ブィストルイ・ウダール）",
        "type": "通常技",
        "command": "2+弱P",
        "startup": 4,
        "active": "4-5",
        "recovery": "11",
        "onHit": 4,
        "onBlock": -1,
        "cancel": "C",
        "damage": "300",
        "comboCorrect": "始動補正20%",
        "driveGain": "250",
        "driveLoseGuard": "-500",
        "driveLosePunish": "-2000",
        "saGain": "300",
        "attribute": "上",
        "note": "連打キャンセル対応"
      },
      {
        "move": "しゃがみ弱K（リョーフキー・ウダール）",
        "type": "通常技",
        "command": "2+弱K",
        "startup": 6,
        "active": "6-7",
        "recovery": "10",
        "onHit": 2,
        "onBlock": -2,
        "cancel": "",
        "damage": "200",
        "comboCorrect": "始動補正20%",
        "driveGain": "250",
        "driveLoseGuard": "-500",
        "driveLosePunish": "-2000",
        "saGain": "300",
        "attribute": "下",
        "note": "連打キャンセル対応 / ※ヴィーハト・チェーニのみキャンセル可能"
      },
      {
        "move": "しゃがみ中P（ズミヤー）",
        "type": "通常技",
        "command": "2+中P",
        "startup": 7,
        "active": "7-10",
        "recovery": "14",
        "onHit": 6,
        "onBlock": -2,
        "cancel": "C",
        "damage": "600",
        "comboCorrect": "",
        "driveGain": "1500",
        "driveLoseGuard": "-3000",
        "driveLosePunish": "-4000",
        "saGain": "500",
        "attribute": "上",
        "note": ""
      },
      {
        "move": "しゃがみ中K（ズローバ）",
        "type": "通常技",
        "command": "2+中K",
        "startup": 9,
        "active": "9-11",
        "recovery": "17",
        "onHit": 3,
        "onBlock": -3,
        "cancel": "",
        "damage": "700",
        "comboCorrect": "始動補正20%",
        "driveGain": "2000",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-6000",
        "saGain": "500",
        "attribute": "下",
        "note": "※ヴィーハト・チェーニのみキャンセル可能"
      },
      {
        "move": "しゃがみ強P（マリートヴァ）",
        "type": "通常技",
        "command": "2+強P",
        "startup": 9,
        "active": "9-14",
        "recovery": "20",
        "onHit": 1,
        "onBlock": -6,
        "cancel": "C",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-5000",
        "driveLosePunish": "-8000",
        "saGain": "1000",
        "attribute": "上",
        "note": "強制立ち効果"
      },
      {
        "move": "しゃがみ強K（ジョーキル）",
        "type": "通常技",
        "command": "2+強K",
        "startup": 10,
        "active": "10-12",
        "recovery": "21",
        "onHit": "D",
        "onBlock": -6,
        "cancel": "",
        "damage": "900",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-5000",
        "driveLosePunish": "-10000",
        "saGain": "1000",
        "attribute": "下",
        "note": "パニッシュカウンター時ダウン時間増加、ハードノックダウン"
      },
      {
        "move": "ジャンプ弱P（ルイースイ）",
        "type": "通常技",
        "command": "（ジャンプ中に）弱P",
        "startup": 5,
        "active": "5-14",
        "recovery": "着地後3",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "300",
        "comboCorrect": "",
        "driveGain": "500",
        "driveLoseGuard": "-1500",
        "driveLosePunish": "-2000",
        "saGain": "300",
        "attribute": "中",
        "note": ""
      },
      {
        "move": "ジャンプ弱K（ヴァローナ）",
        "type": "通常技",
        "command": "（ジャンプ中に）弱K",
        "startup": 6,
        "active": "6-13",
        "recovery": "着地後3",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "300",
        "comboCorrect": "",
        "driveGain": "500",
        "driveLoseGuard": "-1500",
        "driveLosePunish": "-2000",
        "saGain": "300",
        "attribute": "中",
        "note": "めくり性能"
      },
      {
        "move": "ジャンプ中P（ローシャッチ）",
        "type": "通常技",
        "command": "（ジャンプ中に）中P",
        "startup": 12,
        "active": "12-14",
        "recovery": "着地後3",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "700",
        "comboCorrect": "",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-4000",
        "saGain": "500",
        "attribute": "中",
        "note": ""
      },
      {
        "move": "ジャンプ中K（コンダ）",
        "type": "通常技",
        "command": "（ジャンプ中に）中K",
        "startup": 7,
        "active": "7-12",
        "recovery": "着地後3",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "600",
        "comboCorrect": "",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-4000",
        "saGain": "500",
        "attribute": "中",
        "note": "空中ヒット時吹き飛びダウン"
      },
      {
        "move": "ジャンプ強P（イディナローク）",
        "type": "通常技",
        "command": "（ジャンプ中に）強P",
        "startup": 9,
        "active": "9-13",
        "recovery": "着地後3",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-5000",
        "saGain": "1000",
        "attribute": "中",
        "note": "空中カウンター/パニッシュカウンター時叩きつけダウン"
      },
      {
        "move": "ジャンプ強K（ジャール・プチーツァ）",
        "type": "通常技",
        "command": "（ジャンプ中に）強K",
        "startup": 11,
        "active": "11-16",
        "recovery": "着地後3",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-5000",
        "saGain": "1000",
        "attribute": "中",
        "note": ""
      },
      {
        "move": "ギリオチーナ",
        "type": "特殊技",
        "command": "6+中K",
        "startup": 22,
        "active": "22-23",
        "recovery": "19",
        "onHit": 3,
        "onBlock": -3,
        "cancel": "",
        "damage": "700",
        "comboCorrect": "",
        "driveGain": "1500",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-5000",
        "saGain": "500",
        "attribute": "中",
        "note": ""
      },
      {
        "move": "シャーロスチ",
        "type": "特殊技",
        "command": "3+強P",
        "startup": 16,
        "active": "16-18",
        "recovery": "31",
        "onHit": "D",
        "onBlock": -14,
        "cancel": "",
        "damage": "900",
        "comboCorrect": "",
        "driveGain": "3000",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-10000",
        "saGain": "1000",
        "attribute": "下",
        "note": "カウンター/パニッシュカウンター時ダウン時間延長"
      },
      {
        "move": "ヴィリーナ",
        "type": "特殊技",
        "command": "6+強K",
        "startup": 11,
        "active": "11-1611-12, 13-16",
        "recovery": "24",
        "onHit": "D",
        "onBlock": -5,
        "cancel": "C",
        "damage": "900",
        "comboCorrect": "",
        "driveGain": "2500",
        "driveLoseGuard": "-5000",
        "driveLosePunish": "-10000",
        "saGain": "1000",
        "attribute": "上",
        "note": "空中ヒット時吹き飛びダウン"
      },
      {
        "move": "グロームストレルカ（1段目）",
        "type": "特殊技",
        "command": "4+中P",
        "startup": 8,
        "active": "8-10",
        "recovery": "16",
        "onHit": 5,
        "onBlock": -1,
        "cancel": "C",
        "damage": "500",
        "comboCorrect": "",
        "driveGain": "1500",
        "driveLoseGuard": "-3000",
        "driveLosePunish": "-4000",
        "saGain": "400",
        "attribute": "上",
        "note": ""
      },
      {
        "move": "グロームストレルカ（2段目）",
        "type": "特殊技",
        "command": "4+中P>中P",
        "startup": 10,
        "active": "10-12",
        "recovery": "20",
        "onHit": 3,
        "onBlock": -6,
        "cancel": "C",
        "damage": "500",
        "comboCorrect": "コンボ補正20%",
        "driveGain": "800",
        "driveLoseGuard": "-2000",
        "driveLosePunish": "-3000",
        "saGain": "400",
        "attribute": "上",
        "note": ""
      },
      {
        "move": "ジラント",
        "type": "特殊技",
        "command": "強K>強P",
        "startup": 20,
        "active": "20-22",
        "recovery": "20",
        "onHit": 3,
        "onBlock": -3,
        "cancel": "C",
        "damage": "500",
        "comboCorrect": "",
        "driveGain": "1000",
        "driveLoseGuard": "-2000",
        "driveLosePunish": "-4000",
        "saGain": "500",
        "attribute": "上",
        "note": ""
      },
      {
        "move": "ジラントルカー",
        "type": "特殊技",
        "command": "強K>強P>強P",
        "startup": 21,
        "active": "21-23",
        "recovery": "22",
        "onHit": 3,
        "onBlock": -4,
        "cancel": "",
        "damage": "1000",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-5000",
        "driveLosePunish": "-10000",
        "saGain": "1000",
        "attribute": "中",
        "note": ""
      },
      {
        "move": "ジラントナガー",
        "type": "特殊技",
        "command": "強K>強P>強K",
        "startup": 21,
        "active": "21-23",
        "recovery": "22",
        "onHit": 3,
        "onBlock": -4,
        "cancel": "",
        "damage": "1000",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-5000",
        "driveLosePunish": "-10000",
        "saGain": "1000",
        "attribute": "下",
        "note": ""
      },
      {
        "move": "弱 トリグラフ",
        "type": "必殺技",
        "command": "22+弱P",
        "startup": 22,
        "active": "22-31",
        "recovery": "全体 55",
        "onHit": "D",
        "onBlock": -2,
        "cancel": "SA3",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-3000",
        "saGain": "800",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "中 トリグラフ",
        "type": "必殺技",
        "command": "22+中P",
        "startup": 22,
        "active": "22-31",
        "recovery": "全体 55",
        "onHit": "D",
        "onBlock": -2,
        "cancel": "SA3",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-3000",
        "saGain": "800",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "強 トリグラフ",
        "type": "必殺技",
        "command": "22+強P",
        "startup": 22,
        "active": "22-31",
        "recovery": "全体 55",
        "onHit": "D",
        "onBlock": -2,
        "cancel": "SA3",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-3000",
        "saGain": "800",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "OD 弱 トリグラフ",
        "type": "必殺技",
        "command": "22+弱P中P",
        "startup": 20,
        "active": "20-39",
        "recovery": "全体 53",
        "onHit": "D",
        "onBlock": 3,
        "cancel": "SA2",
        "damage": "1000",
        "comboCorrect": "始動補正20％",
        "driveGain": "0",
        "driveLoseGuard": "-3000",
        "driveLosePunish": "-5000",
        "saGain": "1000",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "OD 中 トリグラフ",
        "type": "必殺技",
        "command": "22+弱P強P",
        "startup": 20,
        "active": "20-39",
        "recovery": "全体 53",
        "onHit": "D",
        "onBlock": 3,
        "cancel": "SA2",
        "damage": "1000",
        "comboCorrect": "始動補正20％",
        "driveGain": "0",
        "driveLoseGuard": "-3000",
        "driveLosePunish": "-5000",
        "saGain": "1000",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "OD 強 トリグラフ",
        "type": "必殺技",
        "command": "22+中P強P",
        "startup": 20,
        "active": "20-39",
        "recovery": "全体 53",
        "onHit": "D",
        "onBlock": 3,
        "cancel": "SA2",
        "damage": "1000",
        "comboCorrect": "始動補正20％",
        "driveGain": "0",
        "driveLoseGuard": "-3000",
        "driveLosePunish": "-5000",
        "saGain": "1000",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "弱 ストリボーグ",
        "type": "必殺技",
        "command": "236+弱P",
        "startup": 16,
        "active": "16-21",
        "recovery": "全体 49",
        "onHit": "D",
        "onBlock": -10,
        "cancel": "SA3",
        "damage": "1000",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-3500",
        "driveLosePunish": "-5000",
        "saGain": "800",
        "attribute": "上",
        "note": "ジャストパリィ時はドライブゲージを10000増加 / 飛び道具相殺判定あり（1回）"
      },
      {
        "move": "中 ストリボーグ",
        "type": "必殺技",
        "command": "236+中P",
        "startup": 20,
        "active": "20-2620-22, 24-26",
        "recovery": "全体 53",
        "onHit": "D",
        "onBlock": -8,
        "cancel": "SA3",
        "damage": "1200",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-3500",
        "driveLosePunish": "-5000",
        "saGain": "800",
        "attribute": "上",
        "note": "ジャストパリィ時はドライブゲージを10000増加 / 飛び道具相殺判定あり（1回）"
      },
      {
        "move": "強 ストリボーグ",
        "type": "必殺技",
        "command": "236+強P",
        "startup": 28,
        "active": "28-4228-30, 40-42",
        "recovery": "全体 61",
        "onHit": "D",
        "onBlock": 4,
        "cancel": "SA3",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-3500",
        "driveLosePunish": "-5000",
        "saGain": "800",
        "attribute": "上",
        "note": "ジャストパリィ時はドライブゲージを10000増加 / 飛び道具相殺判定あり（1回） / ジャストパリィ時硬直3F増加"
      },
      {
        "move": "OD ストリボーグ",
        "type": "必殺技",
        "command": "236+PP",
        "startup": 19,
        "active": "19-3019-21, 28-30",
        "recovery": "全体 52",
        "onHit": "D",
        "onBlock": 2,
        "cancel": "SA2",
        "damage": "1000",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "-3500",
        "driveLosePunish": "-5000",
        "saGain": "800",
        "attribute": "上",
        "note": "ジャストパリィ時はドライブゲージを10000増加 / 飛び道具相殺判定あり（1回） / ジャストパリィ時硬直3F増加 / 初段のみSA2/SA3/CAでキャンセル可能"
      },
      {
        "move": "弱 ヴィーハト",
        "type": "必殺技",
        "command": "214+弱P",
        "startup": 150,
        "active": "150-159",
        "recovery": "全体 50",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "800",
        "comboCorrect": "始動補正20％",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-3000",
        "saGain": "1000",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "中 ヴィーハト",
        "type": "必殺技",
        "command": "214+中P",
        "startup": 150,
        "active": "150-159",
        "recovery": "全体 50",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "800",
        "comboCorrect": "始動補正20％",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-3000",
        "saGain": "1000",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "強 ヴィーハト",
        "type": "必殺技",
        "command": "214+強P",
        "startup": 150,
        "active": "150-159",
        "recovery": "全体 50",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "800",
        "comboCorrect": "始動補正20％",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-3000",
        "saGain": "1000",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "OD 弱 ヴィーハト",
        "type": "必殺技",
        "command": "214+弱P中P",
        "startup": 110,
        "active": "110-149110-119, 140-149",
        "recovery": "全体 40",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "1000",
        "comboCorrect": "始動補正20％",
        "driveGain": "0",
        "driveLoseGuard": "-3000",
        "driveLosePunish": "-5000",
        "saGain": "800",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "OD 中 ヴィーハト",
        "type": "必殺技",
        "command": "214+弱P強P",
        "startup": 110,
        "active": "110-149110-119, 140-149",
        "recovery": "全体 40",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "1000",
        "comboCorrect": "始動補正20％",
        "driveGain": "0",
        "driveLoseGuard": "-3000",
        "driveLosePunish": "-5000",
        "saGain": "800",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "OD 強 ヴィーハト",
        "type": "必殺技",
        "command": "214+中P強P",
        "startup": 110,
        "active": "110-149110-119, 140-149",
        "recovery": "全体 40",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "1000",
        "comboCorrect": "始動補正20％",
        "driveGain": "0",
        "driveLoseGuard": "-3000",
        "driveLosePunish": "-5000",
        "saGain": "800",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "ヴィーハト・アクノ",
        "type": "必殺技",
        "command": "（ヴィーハト設置中に）214+弱P / 中P",
        "startup": null,
        "active": "",
        "recovery": "全体 44",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "0",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "",
        "note": "6-25F 完全無敵 / 26F目から空中判定 / 31F目から行動可"
      },
      {
        "move": "ヴィーハト・チェーニ",
        "type": "必殺技",
        "command": "（ヴィーハト設置中に）214+強P",
        "startup": null,
        "active": "",
        "recovery": "全体 40",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "0",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "",
        "note": ""
      },
      {
        "move": "アムネジア",
        "type": "必殺技",
        "command": "22+K",
        "startup": 3,
        "active": "3-20",
        "recovery": "35",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "800",
        "comboCorrect": "始動補正50％※ / 即時補正60％",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-3000",
        "saGain": "1000",
        "attribute": "上・弾",
        "note": "当身成立時にドライブゲージ10000増加 / 当身成立時に飛び道具が発生 / ※コンボの3段目以降に補正がかかる"
      },
      {
        "move": "OD アムネジア",
        "type": "必殺技",
        "command": "22+KK",
        "startup": 1,
        "active": "1-20",
        "recovery": "35",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "1200",
        "comboCorrect": "始動補正50％※ / 即時補正60％",
        "driveGain": "0",
        "driveLoseGuard": "-3000",
        "driveLosePunish": "-5000",
        "saGain": "1200",
        "attribute": "上・弾",
        "note": "当身成立時に飛び道具が発生 / ※コンボの3段目以降に補正がかかる"
      },
      {
        "move": "弱 トルバラン",
        "type": "必殺技",
        "command": "236+弱K",
        "startup": 22,
        "active": "",
        "recovery": "全体 50",
        "onHit": "D",
        "onBlock": -6,
        "cancel": "SA3",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-3000",
        "saGain": "600",
        "attribute": "上・弾",
        "note": "発生は密着で発動した場合の数値"
      },
      {
        "move": "中 トルバラン",
        "type": "必殺技",
        "command": "236+中K",
        "startup": 26,
        "active": "",
        "recovery": "全体 50",
        "onHit": 6,
        "onBlock": -8,
        "cancel": "SA3",
        "damage": "1000",
        "comboCorrect": "始動補正20%",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-3000",
        "saGain": "600",
        "attribute": "中・弾",
        "note": "発生は密着で発動した場合の数値"
      },
      {
        "move": "強 トルバラン",
        "type": "必殺技",
        "command": "236+強K",
        "startup": 26,
        "active": "",
        "recovery": "全体 50",
        "onHit": 6,
        "onBlock": -8,
        "cancel": "SA3",
        "damage": "1000",
        "comboCorrect": "始動補正20%",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-3000",
        "saGain": "600",
        "attribute": "下・弾",
        "note": "発生は密着で発動した場合の数値"
      },
      {
        "move": "OD トルバラン",
        "type": "必殺技",
        "command": "236+KK",
        "startup": 22,
        "active": "",
        "recovery": "全体 50",
        "onHit": "D",
        "onBlock": 25,
        "cancel": "SA2",
        "damage": "800",
        "comboCorrect": "始動補正20%",
        "driveGain": "0",
        "driveLoseGuard": "-5000",
        "driveLosePunish": "-5000",
        "saGain": "800",
        "attribute": "上・弾",
        "note": "発生は密着で発動した場合の数値 / 初段のみSA2/SA3/CAでキャンセル可能"
      },
      {
        "move": "アブニマーチ",
        "type": "必殺技",
        "command": "214+K",
        "startup": 26,
        "active": "",
        "recovery": "全体 72",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "1800",
        "comboCorrect": "即時補正10%",
        "driveGain": "2500",
        "driveLoseGuard": "0",
        "driveLosePunish": "-10000",
        "saGain": "3000",
        "attribute": "投",
        "note": "■クラシック操作 / パニッシュカウンター時のダメージ2070 / 発生、全体は密着で発動した場合の数値 / / ■モダン操作時 / パニッシュカウンター時のダメージ（1656）"
      },
      {
        "move": "OD アブニマーチ",
        "type": "必殺技",
        "command": "214+KK",
        "startup": 26,
        "active": "",
        "recovery": "全体 72",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "2600",
        "comboCorrect": "即時補正10%",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "-10000",
        "saGain": "3000",
        "attribute": "投",
        "note": "■クラシック操作 / パニッシュカウンター時のダメージ2990 / 発生、全体は密着で発動した場合の数値 / / ■モダン操作時 / パニッシュカウンター時のダメージ（2392）"
      },
      {
        "move": "SA1 チェルノボーグ",
        "type": "スーパーアーツ",
        "command": "236236+P",
        "startup": 8,
        "active": "",
        "recovery": "全体 84",
        "onHit": "D",
        "onBlock": -33,
        "cancel": "",
        "damage": "2000",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-5000",
        "saGain": "0",
        "attribute": "上",
        "note": "1-10F 打撃・投げに対して無敵 / 最低保障ダメージ30％ / カウンター/パニッシュカウンターで数値が変動しない"
      },
      {
        "move": "SA2 ラヴーシュカ",
        "type": "スーパーアーツ",
        "command": "214214+P",
        "startup": 29,
        "active": "",
        "recovery": "全体 13",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "2000",
        "comboCorrect": "始動補正25％※ / 即時補正25％",
        "driveGain": "0",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-10000",
        "saGain": "0",
        "attribute": "上中下中",
        "note": "最低保障ダメージ40％ / カウンター/パニッシュカウンターで数値が変動しない / ※コンボの3段目以降に補正がかかる"
      },
      {
        "move": "SA3 ザプリェット",
        "type": "スーパーアーツ",
        "command": "236236+K",
        "startup": 18,
        "active": "18-23",
        "recovery": "62",
        "onHit": "D",
        "onBlock": -50,
        "cancel": "",
        "damage": "4000",
        "comboCorrect": "※即時補正10%",
        "driveGain": "0",
        "driveLoseGuard": "-7500",
        "driveLosePunish": "-15000",
        "saGain": "0",
        "attribute": "上",
        "note": "1-23F 完全無敵 / 最低保障ダメージ50％ / カウンター/パニッシュカウンターで数値が変動しない / ※必殺技キャンセル時のみ適用"
      },
      {
        "move": "CA ザプリェット",
        "type": "スーパーアーツ",
        "command": "（体力25%以下で）236236+K",
        "startup": 18,
        "active": "18-23",
        "recovery": "62",
        "onHit": "D",
        "onBlock": -50,
        "cancel": "",
        "damage": "4500",
        "comboCorrect": "※即時補正10%",
        "driveGain": "0",
        "driveLoseGuard": "-10000",
        "driveLosePunish": "-20000",
        "saGain": "0",
        "attribute": "上",
        "note": "1-23F 完全無敵 / 最低保障ダメージ50％ / カウンター/パニッシュカウンターで数値が変動しない / ※必殺技キャンセル時のみ適用"
      },
      {
        "move": "ラヴィーナ",
        "type": "通常投げ",
        "command": "（近距離で）5 / 6+弱P弱K",
        "startup": 5,
        "active": "5-7",
        "recovery": "23",
        "onHit": "D",
        "onBlock": null,
        "cancel": "",
        "damage": "1200",
        "comboCorrect": "始動補正40% / 即時補正20%",
        "driveGain": "2000",
        "driveLoseGuard": "0",
        "driveLosePunish": "-10000",
        "saGain": "2000",
        "attribute": "投",
        "note": "パニッシュカウンター時以下の性能変化 / ・ダメージ2040 / ・SAゲージ4000増加 / ・ハードノックダウン"
      },
      {
        "move": "ウラガーン",
        "type": "通常投げ",
        "command": "（近距離で）4+弱P弱K",
        "startup": 5,
        "active": "5-7",
        "recovery": "23",
        "onHit": "D",
        "onBlock": null,
        "cancel": "",
        "damage": "1200",
        "comboCorrect": "始動補正40% / 即時補正20%",
        "driveGain": "2000",
        "driveLoseGuard": "0",
        "driveLosePunish": "-10000",
        "saGain": "2000",
        "attribute": "投",
        "note": "パニッシュカウンター時以下の性能変化 / ・ダメージ2040 / ・SAゲージ4000増加 / ・ハードノックダウン"
      },
      {
        "move": "タルナード",
        "type": "通常投げ",
        "command": "（ジャンプ中に）（近距離で）弱P弱K",
        "startup": 5,
        "active": "5-7",
        "recovery": "着地後3",
        "onHit": "D",
        "onBlock": null,
        "cancel": "",
        "damage": "1200",
        "comboCorrect": "即時補正20%",
        "driveGain": "2000",
        "driveLoseGuard": "0",
        "driveLosePunish": "-10000",
        "saGain": "2000",
        "attribute": "投",
        "note": "パニッシュカウンター時以下の性能変化 / ・ダメージ2040 / ・SAゲージ4000増加 / ・ハードノックダウン"
      },
      {
        "move": "前方ステップ",
        "type": "共通システム",
        "command": "66",
        "startup": null,
        "active": "",
        "recovery": "全体 22",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "0",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "",
        "note": ""
      },
      {
        "move": "後方ステップ",
        "type": "共通システム",
        "command": "44",
        "startup": null,
        "active": "",
        "recovery": "全体 23",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "0",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "",
        "note": "1-15F 投げ無敵"
      },
      {
        "move": "ドライブインパクト（エスパーダ）",
        "type": "共通システム",
        "command": "強P強K",
        "startup": 26,
        "active": "26-27",
        "recovery": "35",
        "onHit": "D",
        "onBlock": -3,
        "cancel": "",
        "damage": "800",
        "comboCorrect": "始動補正20%",
        "driveGain": "0",
        "driveLoseGuard": "-5000",
        "driveLosePunish": "-15000",
        "saGain": "0",
        "attribute": "上",
        "note": "1-27F アーマー判定（2回） / パニッシュカウンター、もしくはアーマー成立後にヒットで以下の性能変化 / ・地上ヒット膝崩れ / ・空中ヒットきりもみダウン / ・SAゲージ3000増加"
      },
      {
        "move": "[ガード時]ドライブリバーサル（エクシリオ）",
        "type": "共通システム",
        "command": "（ガード中 or ドライブパリィ成立中に）6+強P強K",
        "startup": 20,
        "active": "20-22",
        "recovery": "26",
        "onHit": "D",
        "onBlock": -6,
        "cancel": "",
        "damage": "500",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "上",
        "note": "リカバリアブルダメージ / 1-22F 完全無敵 / ヒット時硬直5F増加"
      },
      {
        "move": "[起き上がり時]ドライブリバーサル（エクシリオ）",
        "type": "共通システム",
        "command": "（起き上がり時に）6+強P強K",
        "startup": 18,
        "active": "18-20",
        "recovery": "26",
        "onHit": "D",
        "onBlock": -6,
        "cancel": "",
        "damage": "500",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "上",
        "note": "リカバリアブルダメージ / 1-20F 完全無敵 / ヒット時硬直5F増加"
      },
      {
        "move": "ドライブパリィ",
        "type": "共通システム",
        "command": "中P中K",
        "startup": 1,
        "active": "[※2] 1-12",
        "recovery": "33",
        "onHit": null,
        "onBlock": null,
        "cancel": "※1",
        "damage": "0",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "",
        "note": "※1 動作の4F目からドライブラッシュでキャンセル可 / ※2 ボタンホールドでパリィの持続を延長可 / 硬直部分はガードのみ可 / 動作中常に被パニッシュカウンター判定"
      },
      {
        "move": "ジャストパリィ（打撃）",
        "type": "共通システム",
        "command": "ガード方向+中P中K",
        "startup": 1,
        "active": "",
        "recovery": "1",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "0",
        "comboCorrect": "始動補正50％",
        "driveGain": "",
        "driveLoseGuard": "",
        "driveLosePunish": "",
        "saGain": "",
        "attribute": "",
        "note": "相手の攻撃に対応した方向入力を行った状態でパリィを入力し、 / 入力したフレーム、もしくはその次のフレームで攻撃を受けると成立する / （上段/中段攻撃に対して←方向、下段攻撃に対しては↙方向) / 方向が正しくなかった場合は通常のドライブパリィとなり、追加でDゲージが3000増加する / 硬直終了から5Fの間完全無敵 （パリィを継続した場合は無敵にならない） / ジャストパリィを取られた側はキャンセルが出来なくなり、動作終了まで強制パニッシュカウンター"
      },
      {
        "move": "ジャストパリィ（飛び道具）",
        "type": "共通システム",
        "command": "中P中K",
        "startup": 1,
        "active": "",
        "recovery": "10",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "0",
        "comboCorrect": "始動補正50％",
        "driveGain": "",
        "driveLoseGuard": "",
        "driveLosePunish": "",
        "saGain": "",
        "attribute": "",
        "note": "パリィを入力したフレーム、もしくはその次のフレームで攻撃を受けると成立する / 暗転演出が入らない / ジャストパリィを取られた側はキャンセルが出来なくなり、動作終了まで強制パニッシュカウンター / /"
      },
      {
        "move": "パリィドライブラッシュ",
        "type": "共通システム",
        "command": "（ドライブパリィ中に）66",
        "startup": null,
        "active": "",
        "recovery": "全体 45",
        "onHit": null,
        "onBlock": null,
        "cancel": "※",
        "damage": "0",
        "comboCorrect": "乗算補正15％",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "",
        "note": "暗転10F / ※動作9F目から攻撃行動にキャンセル可 / 24F目からパリィ以外の行動でキャンセル可"
      },
      {
        "move": "キャンセルドライブラッシュ",
        "type": "共通システム",
        "command": "（必殺技キャンセル可能な攻撃ヒット中に）66 / (5 / 6)+中P中K",
        "startup": null,
        "active": "",
        "recovery": "全体 46",
        "onHit": null,
        "onBlock": null,
        "cancel": "※",
        "damage": "0",
        "comboCorrect": "乗算補正15％",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "",
        "note": "暗転9F / ※動作10F目から攻撃行動にキャンセル可 / 25F目からパリィ以外の行動でキャンセル可"
      }
    ],
    "ryu": [
      {
        "move": "立ち弱P（ジャブ）",
        "type": "通常技",
        "command": "弱P",
        "startup": 4,
        "active": "4-6",
        "recovery": "7",
        "onHit": 4,
        "onBlock": -1,
        "cancel": "C",
        "damage": "300",
        "comboCorrect": "始動補正20%",
        "driveGain": "250",
        "driveLoseGuard": "-500",
        "driveLosePunish": "-2000",
        "saGain": "300",
        "attribute": "上",
        "note": "連打キャンセル対応"
      },
      {
        "move": "立ち弱K（ローキック）",
        "type": "通常技",
        "command": "弱K",
        "startup": 5,
        "active": "5-7",
        "recovery": "11",
        "onHit": 2,
        "onBlock": -4,
        "cancel": "C",
        "damage": "300",
        "comboCorrect": "始動補正20%",
        "driveGain": "250",
        "driveLoseGuard": "-500",
        "driveLosePunish": "-2000",
        "saGain": "300",
        "attribute": "上",
        "note": ""
      },
      {
        "move": "立ち中P（鉤突き）",
        "type": "通常技",
        "command": "中P",
        "startup": 6,
        "active": "6-9",
        "recovery": "11",
        "onHit": 7,
        "onBlock": -1,
        "cancel": "C",
        "damage": "600",
        "comboCorrect": "",
        "driveGain": "1500",
        "driveLoseGuard": "-3000",
        "driveLosePunish": "-4000",
        "saGain": "500",
        "attribute": "上",
        "note": "空振り時硬直2F増加"
      },
      {
        "move": "立ち中K（横蹴り）",
        "type": "通常技",
        "command": "中K",
        "startup": 9,
        "active": "9-11",
        "recovery": "18",
        "onHit": 4,
        "onBlock": -4,
        "cancel": "",
        "damage": "700",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-6000",
        "saGain": "700",
        "attribute": "上",
        "note": ""
      },
      {
        "move": "立ち強P（正拳突き）",
        "type": "通常技",
        "command": "強P",
        "startup": 10,
        "active": "10-14",
        "recovery": "18",
        "onHit": 4,
        "onBlock": -2,
        "cancel": "C",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-5000",
        "driveLosePunish": "-8000",
        "saGain": "1000",
        "attribute": "上",
        "note": "強制立ち効果"
      },
      {
        "move": "立ち強K（後ろ回し蹴り）",
        "type": "通常技",
        "command": "強K",
        "startup": 12,
        "active": "12-15",
        "recovery": "20",
        "onHit": 9,
        "onBlock": 1,
        "cancel": "",
        "damage": "900",
        "comboCorrect": "",
        "driveGain": "3000",
        "driveLoseGuard": "-6000",
        "driveLosePunish": "-10000",
        "saGain": "1000",
        "attribute": "上",
        "note": "空中ヒット時吹き飛びダウン / パニッシュカウンター時に膝崩れダウンに+36F / 空中パニッシュカウンター時吹き飛び時間延長"
      },
      {
        "move": "しゃがみ弱P（ジャブ）",
        "type": "通常技",
        "command": "2+弱P",
        "startup": 4,
        "active": "4-5",
        "recovery": "9",
        "onHit": 4,
        "onBlock": -1,
        "cancel": "C",
        "damage": "300",
        "comboCorrect": "始動補正20%",
        "driveGain": "250",
        "driveLoseGuard": "-500",
        "driveLosePunish": "-2000",
        "saGain": "300",
        "attribute": "上",
        "note": "連打キャンセル対応"
      },
      {
        "move": "しゃがみ弱K（キック）",
        "type": "通常技",
        "command": "2+弱K",
        "startup": 5,
        "active": "5-6",
        "recovery": "10",
        "onHit": 3,
        "onBlock": -1,
        "cancel": "",
        "damage": "200",
        "comboCorrect": "始動補正20%",
        "driveGain": "250",
        "driveLoseGuard": "-500",
        "driveLosePunish": "-2000",
        "saGain": "300",
        "attribute": "下",
        "note": "連打キャンセル対応"
      },
      {
        "move": "しゃがみ中P（ストレート）",
        "type": "通常技",
        "command": "2+中P",
        "startup": 6,
        "active": "6-9",
        "recovery": "13",
        "onHit": 5,
        "onBlock": 0,
        "cancel": "C",
        "damage": "600",
        "comboCorrect": "",
        "driveGain": "1500",
        "driveLoseGuard": "-3000",
        "driveLosePunish": "-4000",
        "saGain": "500",
        "attribute": "上",
        "note": "空振り時硬直2F増加"
      },
      {
        "move": "しゃがみ中K（くるぶしキック）",
        "type": "通常技",
        "command": "2+中K",
        "startup": 8,
        "active": "8-10",
        "recovery": "19",
        "onHit": 1,
        "onBlock": -6,
        "cancel": "C",
        "damage": "500",
        "comboCorrect": "始動補正20%",
        "driveGain": "1000",
        "driveLoseGuard": "-2000",
        "driveLosePunish": "-4000",
        "saGain": "500",
        "attribute": "下",
        "note": ""
      },
      {
        "move": "しゃがみ強P（突き上げアッパー）",
        "type": "通常技",
        "command": "2+強P",
        "startup": 9,
        "active": "9-14",
        "recovery": "22",
        "onHit": 1,
        "onBlock": -7,
        "cancel": "C",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "3000",
        "driveLoseGuard": "-7500",
        "driveLosePunish": "-10000",
        "saGain": "1200",
        "attribute": "上",
        "note": "キャンセルは持続の1F目がヒットした時のみ / 強制立ち効果"
      },
      {
        "move": "しゃがみ強K（回転足払い）",
        "type": "通常技",
        "command": "2+強K",
        "startup": 9,
        "active": "9-11",
        "recovery": "23",
        "onHit": "D",
        "onBlock": -12,
        "cancel": "",
        "damage": "900",
        "comboCorrect": "",
        "driveGain": "3000",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-10000",
        "saGain": "1000",
        "attribute": "下",
        "note": "パニッシュカウンター時ダウン時間増加、ハードノックダウン"
      },
      {
        "move": "ジャンプ弱P（肘落とし）",
        "type": "通常技",
        "command": "（ジャンプ中に）弱P",
        "startup": 4,
        "active": "4-13",
        "recovery": "着地後3",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "300",
        "comboCorrect": "",
        "driveGain": "500",
        "driveLoseGuard": "-1500",
        "driveLosePunish": "-2000",
        "saGain": "300",
        "attribute": "中",
        "note": ""
      },
      {
        "move": "ジャンプ弱K（ひざ蹴り）",
        "type": "通常技",
        "command": "（ジャンプ中に）弱K",
        "startup": 6,
        "active": "6-15",
        "recovery": "着地後3",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "300",
        "comboCorrect": "",
        "driveGain": "500",
        "driveLoseGuard": "-1500",
        "driveLosePunish": "-2000",
        "saGain": "300",
        "attribute": "中",
        "note": "めくり性能"
      },
      {
        "move": "ジャンプ中P（すくい突き）",
        "type": "通常技",
        "command": "（ジャンプ中に）中P",
        "startup": 8,
        "active": "8-12",
        "recovery": "着地後3",
        "onHit": null,
        "onBlock": null,
        "cancel": "C",
        "damage": "700",
        "comboCorrect": "",
        "driveGain": "1000",
        "driveLoseGuard": "-3000",
        "driveLosePunish": "-5000",
        "saGain": "500",
        "attribute": "中上",
        "note": "空中ヒット時吹き飛びダウン"
      },
      {
        "move": "ジャンプ中K（飛び蹴り）",
        "type": "通常技",
        "command": "（ジャンプ中に）中K",
        "startup": 7,
        "active": "7-12",
        "recovery": "着地後3",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "500",
        "comboCorrect": "",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-4000",
        "saGain": "500",
        "attribute": "中",
        "note": "めくり性能"
      },
      {
        "move": "ジャンプ強P（ストレート）",
        "type": "通常技",
        "command": "（ジャンプ中に）強P",
        "startup": 9,
        "active": "9-14",
        "recovery": "着地後3",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-5000",
        "saGain": "1000",
        "attribute": "中",
        "note": "空中カウンター/パニッシュカウンター時叩きつけダウン"
      },
      {
        "move": "ジャンプ強K（跳び前蹴り）",
        "type": "通常技",
        "command": "（ジャンプ中に）強K",
        "startup": 10,
        "active": "10-17",
        "recovery": "着地後3",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-5000",
        "saGain": "1000",
        "attribute": "中",
        "note": ""
      },
      {
        "move": "鎖骨割り",
        "type": "特殊技",
        "command": "6+中P",
        "startup": 20,
        "active": "20-23",
        "recovery": "19",
        "onHit": 3,
        "onBlock": -3,
        "cancel": "",
        "damage": "600",
        "comboCorrect": "",
        "driveGain": "1500",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-5000",
        "saGain": "500",
        "attribute": "※中上",
        "note": "※初段が空振り時のみ2段目が中段判定"
      },
      {
        "move": "鳩尾砕き",
        "type": "特殊技",
        "command": "6+強P",
        "startup": 20,
        "active": "20-24",
        "recovery": "16",
        "onHit": 6,
        "onBlock": 3,
        "cancel": "",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "2500",
        "driveLoseGuard": "-5000",
        "driveLosePunish": "-8000",
        "saGain": "1000",
        "attribute": "上",
        "note": ""
      },
      {
        "move": "上げ突き",
        "type": "特殊技",
        "command": "4+強P",
        "startup": 7,
        "active": "7-10",
        "recovery": "26",
        "onHit": 1,
        "onBlock": -13,
        "cancel": "C",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-5000",
        "driveLosePunish": "-8000",
        "saGain": "1000",
        "attribute": "上",
        "note": "キャンセルは持続の1F目がヒットした時のみ / 強制立ち効果"
      },
      {
        "move": "かかと落とし",
        "type": "特殊技",
        "command": "4+強K",
        "startup": 10,
        "active": "10-2310-14, 20-23",
        "recovery": "21",
        "onHit": 0,
        "onBlock": -4,
        "cancel": "C",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "3500",
        "driveLoseGuard": "-3000",
        "driveLosePunish": "-6000",
        "saGain": "1000",
        "attribute": "上",
        "note": "1段目強制立ち効果 / 2段目空中ヒット時床バウンド"
      },
      {
        "move": "旋風脚",
        "type": "特殊技",
        "command": "6+強K",
        "startup": 16,
        "active": "16-19",
        "recovery": "20",
        "onHit": 2,
        "onBlock": -4,
        "cancel": "※",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "2500",
        "driveLoseGuard": "-5000",
        "driveLosePunish": "-8000",
        "saGain": "1000",
        "attribute": "上",
        "note": "※空中竜巻旋風脚(OD版を含む)でキャンセル可能"
      },
      {
        "move": "上段二連撃",
        "type": "特殊技",
        "command": "強P>強K",
        "startup": 9,
        "active": "9-12",
        "recovery": "20",
        "onHit": "D",
        "onBlock": -8,
        "cancel": "※",
        "damage": "1000",
        "comboCorrect": "",
        "driveGain": "2500",
        "driveLoseGuard": "-7000",
        "driveLosePunish": "-10000",
        "saGain": "1000",
        "attribute": "上",
        "note": "※ヒット時、電刃錬気でのみキャンセル可能 / クラシック操作:↓+P、モダン操作:↓＋攻撃"
      },
      {
        "move": "不破三連撃（2段目）",
        "type": "特殊技",
        "command": "中P>弱K",
        "startup": 5,
        "active": "5-7",
        "recovery": "16",
        "onHit": 1,
        "onBlock": -4,
        "cancel": "",
        "damage": "300",
        "comboCorrect": "",
        "driveGain": "1000",
        "driveLoseGuard": "-1000",
        "driveLosePunish": "-2000",
        "saGain": "500",
        "attribute": "上",
        "note": ""
      },
      {
        "move": "不破三連撃（3段目）",
        "type": "特殊技",
        "command": "中P>弱K>強K",
        "startup": 17,
        "active": "17-20",
        "recovery": "20",
        "onHit": "D",
        "onBlock": -8,
        "cancel": "※",
        "damage": "900",
        "comboCorrect": "",
        "driveGain": "2500",
        "driveLoseGuard": "-3000",
        "driveLosePunish": "-10000",
        "saGain": "1000",
        "attribute": "上",
        "note": "※ヒット時、電刃錬気でのみキャンセル可能 / クラシック操作:↓+P、モダン操作:↓＋攻撃"
      },
      {
        "move": "弱 波動拳",
        "type": "必殺技",
        "command": "236+弱P",
        "startup": 16,
        "active": "",
        "recovery": "全体 47",
        "onHit": 2,
        "onBlock": -5,
        "cancel": "SA3",
        "damage": "700",
        "comboCorrect": "",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-3000",
        "saGain": "600",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "中 波動拳",
        "type": "必殺技",
        "command": "236+中P",
        "startup": 14,
        "active": "",
        "recovery": "全体 47",
        "onHit": 0,
        "onBlock": -7,
        "cancel": "SA3",
        "damage": "700",
        "comboCorrect": "",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-3000",
        "saGain": "600",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "強 波動拳",
        "type": "必殺技",
        "command": "236+強P",
        "startup": 12,
        "active": "",
        "recovery": "全体 47",
        "onHit": -2,
        "onBlock": -9,
        "cancel": "SA3",
        "damage": "700",
        "comboCorrect": "",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-3000",
        "saGain": "600",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "[電刃錬気]波動拳",
        "type": "必殺技",
        "command": "236+P",
        "startup": 12,
        "active": "",
        "recovery": "全体 40",
        "onHit": "D",
        "onBlock": -1,
        "cancel": "SA3",
        "damage": "1000",
        "comboCorrect": "始動補正20％ / コンボ補正20％",
        "driveGain": "1000",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-3000",
        "saGain": "600",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "OD 波動拳",
        "type": "必殺技",
        "command": "236+PP",
        "startup": 12,
        "active": "",
        "recovery": "全体 40",
        "onHit": "D",
        "onBlock": -1,
        "cancel": "SA2",
        "damage": "1000",
        "comboCorrect": "始動補正20％ / コンボ補正20％",
        "driveGain": "0",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-5000",
        "saGain": "600",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "[電刃錬気]OD 波動拳",
        "type": "必殺技",
        "command": "236+PP",
        "startup": 12,
        "active": "",
        "recovery": "全体 38",
        "onHit": "D",
        "onBlock": 2,
        "cancel": "SA2",
        "damage": "1200",
        "comboCorrect": "始動補正20％ / コンボ補正20％",
        "driveGain": "0",
        "driveLoseGuard": "-3750",
        "driveLosePunish": "-7000",
        "saGain": "900",
        "attribute": "上・弾",
        "note": ""
      },
      {
        "move": "弱 昇龍拳",
        "type": "必殺技",
        "command": "623+弱P",
        "startup": 5,
        "active": "5-14",
        "recovery": "21+着地後12",
        "onHit": "D",
        "onBlock": -23,
        "cancel": "SA3",
        "damage": "※1100",
        "comboCorrect": "始動補正30%",
        "driveGain": "2000",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-5000",
        "saGain": "1000",
        "attribute": "上",
        "note": "1-14F 空中判定の打撃・空弾属性に対して無敵 / 7-34F 空中判定 / ※持続の3F目以降は個別ダメージ（800）"
      },
      {
        "move": "中 昇龍拳",
        "type": "必殺技",
        "command": "623+中P",
        "startup": 6,
        "active": "6-15",
        "recovery": "30+着地後12",
        "onHit": "D",
        "onBlock": -32,
        "cancel": "SA3",
        "damage": "※1200",
        "comboCorrect": "始動補正30%",
        "driveGain": "2000",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-5000",
        "saGain": "1000",
        "attribute": "上",
        "note": "1-9F 空中判定の打撃・空弾属性に対して無敵 / 8-44F 空中判定 / ※持続の3F目以降は個別ダメージ（800）"
      },
      {
        "move": "強 昇龍拳",
        "type": "必殺技",
        "command": "623+強P",
        "startup": 7,
        "active": "7-16",
        "recovery": "34+着地後12",
        "onHit": "D",
        "onBlock": -36,
        "cancel": "SA3",
        "damage": "※1400",
        "comboCorrect": "始動補正30%",
        "driveGain": "2000",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-5000",
        "saGain": "1000",
        "attribute": "上",
        "note": "1-8F 空中判定の打撃・空弾属性に対して無敵 / 9-49F 空中判定 / ※持続の2F目以降は個別ダメージ（800）"
      },
      {
        "move": "OD 昇龍拳",
        "type": "必殺技",
        "command": "623+PP",
        "startup": 6,
        "active": "6-156-7,8-15",
        "recovery": "37+着地後15",
        "onHit": "D",
        "onBlock": -40,
        "cancel": "",
        "damage": "1600",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "-2000",
        "driveLosePunish": "0",
        "saGain": "1000",
        "attribute": "上",
        "note": "1-8F 完全無敵 / 8-51F 空中判定"
      },
      {
        "move": "弱 竜巻旋風脚",
        "type": "必殺技",
        "command": "214+弱K",
        "startup": 12,
        "active": "12-14",
        "recovery": "14+着地後18",
        "onHit": "D",
        "onBlock": -15,
        "cancel": "",
        "damage": "900",
        "comboCorrect": "",
        "driveGain": "3000",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-5000",
        "saGain": "1200",
        "attribute": "上",
        "note": "5-28F 空中判定"
      },
      {
        "move": "中 竜巻旋風脚",
        "type": "必殺技",
        "command": "214+中K",
        "startup": 14,
        "active": "14-3014-15, 29-30",
        "recovery": "11+着地後20",
        "onHit": "D",
        "onBlock": -13,
        "cancel": "",
        "damage": "1000",
        "comboCorrect": "",
        "driveGain": "3500",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-5000",
        "saGain": "1300",
        "attribute": "上",
        "note": "8-41F 空中判定"
      },
      {
        "move": "強 竜巻旋風脚",
        "type": "必殺技",
        "command": "214+強K",
        "startup": 16,
        "active": "16-4716-17, 31-32, 46-47",
        "recovery": "14+着地後17",
        "onHit": "D",
        "onBlock": -13,
        "cancel": "",
        "damage": "1200",
        "comboCorrect": "",
        "driveGain": "4000",
        "driveLoseGuard": "-2000",
        "driveLosePunish": "-5000",
        "saGain": "1400",
        "attribute": "上",
        "note": "10-61F 空中判定"
      },
      {
        "move": "OD 竜巻旋風脚",
        "type": "必殺技",
        "command": "214+KK",
        "startup": 13,
        "active": "13-3713-14, 19-20, 25-26, 30-31, 36-37",
        "recovery": "10+着地後13",
        "onHit": "D",
        "onBlock": -14,
        "cancel": "",
        "damage": "1000",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-5000",
        "saGain": "1000",
        "attribute": "上",
        "note": "5-47F 空中判定"
      },
      {
        "move": "空中竜巻旋風脚",
        "type": "必殺技",
        "command": "（前ジャンプ中に）214+K",
        "startup": 11,
        "active": "11-2711-12,18-19,26-27",
        "recovery": "着地後16",
        "onHit": "D",
        "onBlock": null,
        "cancel": "",
        "damage": "900",
        "comboCorrect": "始動補正30%",
        "driveGain": "2000",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-5000",
        "saGain": "600",
        "attribute": "上",
        "note": ""
      },
      {
        "move": "OD 空中竜巻旋風脚",
        "type": "必殺技",
        "command": "（前ジャンプ中に）214+KK",
        "startup": 11,
        "active": "11-2811-12, 14-16, 18-20, 22-24, 27-28",
        "recovery": "着地後16",
        "onHit": "D",
        "onBlock": null,
        "cancel": "",
        "damage": "1500",
        "comboCorrect": "コンボ補正25%",
        "driveGain": "0",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-5000",
        "saGain": "600",
        "attribute": "上",
        "note": ""
      },
      {
        "move": "弱 上段足刀蹴り",
        "type": "必殺技",
        "command": "236+弱K",
        "startup": 14,
        "active": "14-19",
        "recovery": "22",
        "onHit": "D",
        "onBlock": -11,
        "cancel": "SA3",
        "damage": "1100",
        "comboCorrect": "",
        "driveGain": "3000",
        "driveLoseGuard": "-6000",
        "driveLosePunish": "-5000",
        "saGain": "1400",
        "attribute": "上",
        "note": ""
      },
      {
        "move": "中 上段足刀蹴り",
        "type": "必殺技",
        "command": "236+中K",
        "startup": 18,
        "active": "18-26",
        "recovery": "19",
        "onHit": "D",
        "onBlock": -8,
        "cancel": "SA3",
        "damage": "1200",
        "comboCorrect": "",
        "driveGain": "3500",
        "driveLoseGuard": "-6000",
        "driveLosePunish": "-7000",
        "saGain": "1400",
        "attribute": "上",
        "note": ""
      },
      {
        "move": "強 上段足刀蹴り",
        "type": "必殺技",
        "command": "236+強K",
        "startup": 27,
        "active": "27-35",
        "recovery": "15",
        "onHit": "D",
        "onBlock": -3,
        "cancel": "SA3",
        "damage": "1300",
        "comboCorrect": "",
        "driveGain": "5000",
        "driveLoseGuard": "-10000",
        "driveLosePunish": "-10000",
        "saGain": "1400",
        "attribute": "上",
        "note": "パニッシュカウンター時吹き飛び時間延長"
      },
      {
        "move": "OD 上段足刀蹴り",
        "type": "必殺技",
        "command": "236+KK",
        "startup": 17,
        "active": "17-21",
        "recovery": "33",
        "onHit": "D",
        "onBlock": -18,
        "cancel": "SA2",
        "damage": "800",
        "comboCorrect": "コンボ補正15%",
        "driveGain": "0",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-5000",
        "saGain": "1200",
        "attribute": "上",
        "note": ""
      },
      {
        "move": "弱 波掌撃",
        "type": "必殺技",
        "command": "214+弱P",
        "startup": 12,
        "active": "12-17",
        "recovery": "18",
        "onHit": 2,
        "onBlock": -3,
        "cancel": "SA3",
        "damage": "700",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-2000",
        "driveLosePunish": "-5000",
        "saGain": "800",
        "attribute": "上",
        "note": "カウンター/パニッシュカウンター時吹き飛びダウン / 飛び道具相殺判定あり（1回）"
      },
      {
        "move": "中 波掌撃",
        "type": "必殺技",
        "command": "214+中P",
        "startup": 19,
        "active": "19-24",
        "recovery": "17",
        "onHit": 2,
        "onBlock": -6,
        "cancel": "SA3",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-6000",
        "driveLosePunish": "-5000",
        "saGain": "800",
        "attribute": "上",
        "note": "カウンター/パニッシュカウンター時吹き飛びダウン / 飛び道具相殺判定あり（1回）"
      },
      {
        "move": "強 波掌撃",
        "type": "必殺技",
        "command": "214+強P",
        "startup": 30,
        "active": "30-34.35",
        "recovery": "19",
        "onHit": "D",
        "onBlock": 2,
        "cancel": "SA3",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-6000",
        "driveLosePunish": "-5000",
        "saGain": "1100",
        "attribute": "上",
        "note": "飛び道具相殺判定あり（2回）"
      },
      {
        "move": "[電刃錬気]波掌撃",
        "type": "必殺技",
        "command": "214+P",
        "startup": 20,
        "active": "20-24.25",
        "recovery": "19",
        "onHit": "D",
        "onBlock": 3,
        "cancel": "SA3",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "2000",
        "driveLoseGuard": "-6000",
        "driveLosePunish": "-5000",
        "saGain": "1100",
        "attribute": "上",
        "note": "飛び道具相殺判定あり（2回）"
      },
      {
        "move": "OD 波掌撃",
        "type": "必殺技",
        "command": "214+PP",
        "startup": 18,
        "active": "18-22",
        "recovery": "20",
        "onHit": 3,
        "onBlock": 3,
        "cancel": "SA2",
        "damage": "1100",
        "comboCorrect": "コンボ補正20％",
        "driveGain": "0",
        "driveLoseGuard": "-6000",
        "driveLosePunish": "-5000",
        "saGain": "900",
        "attribute": "上",
        "note": "飛び道具相殺判定あり（1回）"
      },
      {
        "move": "[電刃錬気]OD 波掌撃",
        "type": "必殺技",
        "command": "214+PP",
        "startup": 18,
        "active": "18-23",
        "recovery": "19",
        "onHit": "D",
        "onBlock": 4,
        "cancel": "SA2",
        "damage": "800",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "-6000",
        "driveLosePunish": "-5000",
        "saGain": "1100",
        "attribute": "上",
        "note": "ヒット時に膝崩れダウンに＋39 / 飛び道具相殺判定あり（1回）"
      },
      {
        "move": "電刃錬気",
        "type": "必殺技",
        "command": "22+P",
        "startup": null,
        "active": "",
        "recovery": "全体 52",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "0",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "",
        "note": "51F目で電刃錬気を1つストック（1つまでストック可能） / 波動拳、波掌撃、真空波動拳、真波掌撃の性能が強化される"
      },
      {
        "move": "SA1 真空波動拳",
        "type": "スーパーアーツ",
        "command": "236236+P",
        "startup": 7,
        "active": "",
        "recovery": "全体 86",
        "onHit": "D",
        "onBlock": -24,
        "cancel": "",
        "damage": "2000",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-5000",
        "saGain": "0",
        "attribute": "上・弾",
        "note": "1-8F 打撃・投げに対して無敵 / カウンター/パニッシュカウンターで数値が変動しない / 最低保障ダメージ30％"
      },
      {
        "move": "[電刃錬気]SA1 真空波動拳",
        "type": "スーパーアーツ",
        "command": "236236+P",
        "startup": 7,
        "active": "",
        "recovery": "全体 89",
        "onHit": "D",
        "onBlock": -24,
        "cancel": "",
        "damage": "2400",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "-2500",
        "driveLosePunish": "-5000",
        "saGain": "0",
        "attribute": "上・弾",
        "note": "1-8F 打撃・投げに対して無敵 / カウンター/パニッシュカウンターで数値が変動しない / 最低保障ダメージ30％"
      },
      {
        "move": "SA2 真波掌撃（Lv1）",
        "type": "スーパーアーツ",
        "command": "214214+P",
        "startup": 12,
        "active": "12-17",
        "recovery": "39",
        "onHit": "D",
        "onBlock": -20,
        "cancel": "",
        "damage": "2800",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-10000",
        "saGain": "0",
        "attribute": "上",
        "note": "1-13F 完全無敵 / ボタンをホールドする事で性能変化 / 7F以上ボタンを押して離すとLv2が発動 / 39F以上ボタンを押して離すとLv3が発動 / カウンター/パニッシュカウンターで数値が変動しない / 最低保障ダメージ40％"
      },
      {
        "move": "SA2 真波掌撃（Lv2）",
        "type": "スーパーアーツ",
        "command": "214214+P",
        "startup": 20,
        "active": "20-25",
        "recovery": "39",
        "onHit": "D",
        "onBlock": -20,
        "cancel": "",
        "damage": "2900",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "-6000",
        "driveLosePunish": "-10000",
        "saGain": "0",
        "attribute": "上",
        "note": "1-9F 完全無敵 / ボタンをホールドする事で性能変化 / 7F以上ボタンを押して離すとLv2が発動 / 39F以上ボタンを押して離すとLv3が発動 / カウンター/パニッシュカウンターで数値が変動しない / 最低保障ダメージ40％"
      },
      {
        "move": "SA2 真波掌撃（Lv3）",
        "type": "スーパーアーツ",
        "command": "214214+P",
        "startup": 70,
        "active": "70-75",
        "recovery": "39",
        "onHit": "D",
        "onBlock": -20,
        "cancel": "",
        "damage": "3000",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "-10000",
        "driveLosePunish": "-10000",
        "saGain": "0",
        "attribute": "上",
        "note": "1-9F 完全無敵 / ボタンをホールドする事で性能変化 / 7F以上ボタンを押して離すとLv2が発動 / 39F以上ボタンを押して離すとLv3が発動 / カウンター/パニッシュカウンターで数値が変動しない / 最低保障ダメージ40％"
      },
      {
        "move": "[電刃錬気]SA2 真波掌撃（Lv1）",
        "type": "スーパーアーツ",
        "command": "214214+P",
        "startup": 12,
        "active": "12-17",
        "recovery": "39",
        "onHit": "D",
        "onBlock": -20,
        "cancel": "",
        "damage": "3200",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "-4000",
        "driveLosePunish": "-10000",
        "saGain": "0",
        "attribute": "上",
        "note": "1-13F 完全無敵 / ボタンをホールドする事で性能変化 / 7F以上ボタンを押して離すとLv2が発動 / 39F以上ボタンを押して離すとLv3が発動 / カウンター/パニッシュカウンターで数値が変動しない / 最低保障ダメージ40％"
      },
      {
        "move": "[電刃錬気]SA2 真波掌撃（Lv2）",
        "type": "スーパーアーツ",
        "command": "214214+P",
        "startup": 20,
        "active": "20-25",
        "recovery": "39",
        "onHit": "D",
        "onBlock": -20,
        "cancel": "",
        "damage": "3300",
        "comboCorrect": "コンボ補正20％",
        "driveGain": "0",
        "driveLoseGuard": "-6000",
        "driveLosePunish": "-10000",
        "saGain": "0",
        "attribute": "上",
        "note": "1-9F 完全無敵 / ボタンをホールドする事で性能変化 / 7F以上ボタンを押して離すとLv2が発動 / 39F以上ボタンを押して離すとLv3が発動 / カウンター/パニッシュカウンターで数値が変動しない / 最低保障ダメージ40％"
      },
      {
        "move": "[電刃錬気]SA2 真波掌撃（Lv3）",
        "type": "スーパーアーツ",
        "command": "214214+P",
        "startup": 70,
        "active": "70-75",
        "recovery": "39",
        "onHit": "D",
        "onBlock": -20,
        "cancel": "",
        "damage": "3400",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "-10000",
        "driveLosePunish": "-10000",
        "saGain": "0",
        "attribute": "上",
        "note": "1-9F 完全無敵 / ボタンをホールドする事で性能変化 / 7F以上ボタンを押して離すとLv2が発動 / 39F以上ボタンを押して離すとLv3が発動 / カウンター/パニッシュカウンターで数値が変動しない / 最低保障ダメージ40％"
      },
      {
        "move": "SA3 真・昇龍拳",
        "type": "スーパーアーツ",
        "command": "236236+K",
        "startup": 5,
        "active": "5-165-6, 7-8, 9-10, 11-12, 13-14, 15-16",
        "recovery": "71",
        "onHit": "D",
        "onBlock": -52,
        "cancel": "",
        "damage": "4000",
        "comboCorrect": "※即時補正10%",
        "driveGain": "0",
        "driveLoseGuard": "-7500",
        "driveLosePunish": "-15000",
        "saGain": "0",
        "attribute": "上",
        "note": "1-16F 完全無敵 / 最低保障ダメージ50％ / カウンター/パニッシュカウンターで数値が変動しない / ※必殺技キャンセル時のみ適用"
      },
      {
        "move": "CA 真・昇龍拳",
        "type": "スーパーアーツ",
        "command": "（体力25%以下で）236236+K",
        "startup": 5,
        "active": "5-165-6, 7-8, 9-10, 11-12, 13-14, 15-16",
        "recovery": "71",
        "onHit": "D",
        "onBlock": -52,
        "cancel": "",
        "damage": "4500",
        "comboCorrect": "※即時補正10%",
        "driveGain": "0",
        "driveLoseGuard": "-10000",
        "driveLosePunish": "-20000",
        "saGain": "0",
        "attribute": "上",
        "note": "1-16F 完全無敵 / 最低保障ダメージ50％ / カウンター/パニッシュカウンターで数値が変動しない / ※必殺技キャンセル時のみ適用"
      },
      {
        "move": "背負い投げ",
        "type": "通常投げ",
        "command": "（近距離で）5 / 6+弱P弱K",
        "startup": 5,
        "active": "5-7",
        "recovery": "23",
        "onHit": "D",
        "onBlock": null,
        "cancel": "",
        "damage": "1200",
        "comboCorrect": "即時補正20%",
        "driveGain": "2000",
        "driveLoseGuard": "0",
        "driveLosePunish": "-10000",
        "saGain": "2000",
        "attribute": "投",
        "note": "パニッシュカウンター時以下の性能変化 / ・ダメージ2040 / ・SAゲージ4000増加 / ・ハードノックダウン"
      },
      {
        "move": "巴投げ",
        "type": "通常投げ",
        "command": "（近距離で）4+弱P弱K",
        "startup": 5,
        "active": "5-7",
        "recovery": "23",
        "onHit": "D",
        "onBlock": null,
        "cancel": "",
        "damage": "1200",
        "comboCorrect": "即時補正20%",
        "driveGain": "2000",
        "driveLoseGuard": "0",
        "driveLosePunish": "-10000",
        "saGain": "2000",
        "attribute": "投",
        "note": "パニッシュカウンター時以下の性能変化 / ・ダメージ2040 / ・SAゲージ4000増加 / ・ハードノックダウン"
      },
      {
        "move": "前方ステップ",
        "type": "共通システム",
        "command": "66",
        "startup": null,
        "active": "",
        "recovery": "全体 19",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "0",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "",
        "note": ""
      },
      {
        "move": "後方ステップ",
        "type": "共通システム",
        "command": "44",
        "startup": null,
        "active": "",
        "recovery": "全体 23",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "0",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "",
        "note": "1-15F 投げ無敵"
      },
      {
        "move": "ドライブインパクト（震撃）",
        "type": "共通システム",
        "command": "強P強K",
        "startup": 26,
        "active": "26-27",
        "recovery": "35",
        "onHit": null,
        "onBlock": -3,
        "cancel": "",
        "damage": "800",
        "comboCorrect": "始動補正20%",
        "driveGain": "0",
        "driveLoseGuard": "-5000",
        "driveLosePunish": "-15000",
        "saGain": "0",
        "attribute": "上",
        "note": "1-27F アーマー判定（2回） / ヒットバックでステージ端に到達すると壁やられが発生 / パニッシュカウンター、もしくはアーマー成立後にヒットで以下の性能変化 / ・地上ヒット膝崩れ / ・空中ヒット吹き飛び時間増加 / ・SAゲージ3000増加"
      },
      {
        "move": "[ガード時]ドライブリバーサル（胸尖打ち）",
        "type": "共通システム",
        "command": "（ガード中 or ドライブパリィ成立中に）6+強P強K",
        "startup": 20,
        "active": "20-22",
        "recovery": "26",
        "onHit": "D",
        "onBlock": -6,
        "cancel": "",
        "damage": "500",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "上",
        "note": "リカバリアブルダメージ / 1-22F 完全無敵 / ヒット時硬直5F増加"
      },
      {
        "move": "[起き上がり時]ドライブリバーサル（胸尖打ち）",
        "type": "共通システム",
        "command": "（起き上がり時に）6+強P強K",
        "startup": 18,
        "active": "18-20",
        "recovery": "26",
        "onHit": "D",
        "onBlock": -6,
        "cancel": "",
        "damage": "500",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "上",
        "note": "リカバリアブルダメージ / 1-20F 完全無敵 / ヒット時硬直5F増加"
      },
      {
        "move": "ドライブパリィ",
        "type": "共通システム",
        "command": "中P中K",
        "startup": 1,
        "active": "[※2] 1-12",
        "recovery": "33",
        "onHit": null,
        "onBlock": null,
        "cancel": "※1",
        "damage": "0",
        "comboCorrect": "",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "",
        "note": "※1 動作の4F目からドライブラッシュでキャンセル可 / ※2 ボタンホールドでパリィの持続を延長可 / 硬直部分はガードのみ可 / 動作中常に被パニッシュカウンター判定"
      },
      {
        "move": "ジャストパリィ（打撃）",
        "type": "共通システム",
        "command": "ガード方向+中P中K",
        "startup": 1,
        "active": "",
        "recovery": "1",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "0",
        "comboCorrect": "始動補正50％",
        "driveGain": "",
        "driveLoseGuard": "",
        "driveLosePunish": "",
        "saGain": "",
        "attribute": "",
        "note": "相手の攻撃に対応した方向入力を行った状態でパリィを入力し、 / 入力したフレーム、もしくはその次のフレームで攻撃を受けると成立する / （上段/中段攻撃に対して←方向、下段攻撃に対しては↙方向) / 方向が正しくなかった場合は通常のドライブパリィとなり、追加でDゲージが3000増加する / 硬直終了から5Fの間完全無敵 （パリィを継続した場合は無敵にならない） / ジャストパリィを取られた側はキャンセルが出来なくなり、動作終了まで強制パニッシュカウンター"
      },
      {
        "move": "ジャストパリィ（飛び道具）",
        "type": "共通システム",
        "command": "中P中K",
        "startup": 1,
        "active": "",
        "recovery": "10",
        "onHit": null,
        "onBlock": null,
        "cancel": "",
        "damage": "0",
        "comboCorrect": "始動補正50％",
        "driveGain": "",
        "driveLoseGuard": "",
        "driveLosePunish": "",
        "saGain": "",
        "attribute": "",
        "note": "パリィを入力したフレーム、もしくはその次のフレームで攻撃を受けると成立する / 暗転演出が入らない / ジャストパリィを取られた側はキャンセルが出来なくなり、動作終了まで強制パニッシュカウンター"
      },
      {
        "move": "パリィドライブラッシュ",
        "type": "共通システム",
        "command": "（ドライブパリィ中に）66",
        "startup": null,
        "active": "",
        "recovery": "全体 45",
        "onHit": null,
        "onBlock": null,
        "cancel": "※",
        "damage": "0",
        "comboCorrect": "乗算補正15％",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "",
        "note": "暗転10F / ※動作9F目から攻撃行動にキャンセル可 / 24F目からパリィ以外の行動でキャンセル可"
      },
      {
        "move": "キャンセルドライブラッシュ",
        "type": "共通システム",
        "command": "（必殺技キャンセル可能な攻撃ヒット中に）66 / (5 / 6)+中P中K",
        "startup": null,
        "active": "",
        "recovery": "全体 46",
        "onHit": null,
        "onBlock": null,
        "cancel": "※",
        "damage": "0",
        "comboCorrect": "乗算補正15％",
        "driveGain": "0",
        "driveLoseGuard": "0",
        "driveLosePunish": "0",
        "saGain": "0",
        "attribute": "",
        "note": "暗転9F / ※動作10F目から攻撃行動にキャンセル可 / 25F目からパリィ以外の行動でキャンセル可"
      }
    ]
  },
  "setplays": {
    "jp": [],
    "ryu": [
      {
        "id": "ryu-s1",
        "situation": "中央 強昇龍ダウン後",
        "setup": "前ステップ x2",
        "mixup": "打撃(2中K) / 投げ の二択",
        "video": "",
        "timestamp": "",
        "note": "基本の重ね。"
      }
    ]
  }
};

if (typeof module !== "undefined") { module.exports = SF6_DATA; }
